routes/web.php
<?php

use App\Http\Controllers\BlogsController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\CommentsController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\UsersController;
use Illuminate\Routing\RouteUrlGenerator;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [FrontendController::class, 'index'])->name('home');

Route::get('/categories/{category}/blogs', [FrontendController::class, 'category'])->name('frontend.category');
Route::get('/tags/{tag}/blogs', [FrontendController::class, 'tag'])->name('frontend.tag');
Route::get('/blogs/{blog}', [FrontendController::class, 'show'])->name('frontend.blogs.show');



Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    Route::prefix("/admin")->name('admin.')->group(function(){

        Route::get('/dashboard', function(){
            return view('admin.dashboard');
        })->name('dashboard');

        Route::get('/categories/trashed', [CategoriesController::class, 'trashed'])->name('categories.trashed');
        Route::resource('categories', CategoriesController::class)->except(['show']);
        Route::delete('/categories/{category}/trash', [CategoriesController::class, 'trash'])->name('categories.trash');
        Route::put('/categories/{category}/restore', [CategoriesController::class, 'restore'])->name('categories.restore');

        Route::get('/tags/trashed', [TagsController::class, 'trashed'])->name('tags.trashed');
        Route::resource('tags', TagsController::class)->except(['show']);
        Route::delete('/tags/{tag}/trash', [TagsController::class, 'trash'])->name('tags.trash');
        Route::put('/tags/{tag}/restore', [TagsController::class, 'restore'])->name('tags.restore');

        Route::get('/blogs/trashed', [BlogsController::class, 'trashed'])->name('blogs.trashed');
        Route::resource('blogs', BlogsController::class)->except(['show']);
        Route::delete('/blogs/{blog}/trash', [BlogsController::class, 'trash'])->name('blogs.trash');
        Route::put('/blogs/{blog}/restore', [BlogsController::class, 'restore'])->name('blogs.restore');
        Route::put('/blogs/{blog}/approve', [BlogsController::class, 'approve'])->name('blogs.approve');
        Route::put('/blogs/{blog}/unapprove', [BlogsController::class, 'unapprove'])->name('blogs.unapprove');
        Route::put('/blogs/{blog}/publish', [BlogsController::class, 'publish'])->name('blogs.publish');
        Route::put('/blogs/{blog}/unpublish', [BlogsController::class, 'unpublish'])->name('blogs.unpublish');


        Route::get('/users', [UsersController::class, 'index'])->name('users.index');
        Route::put('/users/{user}/verify', [UsersController::class, 'verify'])->name('users.verify');
        Route::put('/users/{user}/revoke', [UsersController::class, 'revoke'])->name('users.revoke');
        Route::put('/users/{user}/makeadmin', [UsersController::class, 'admin'])->name('users.makeadmin');

        Route::resource('/comments', CommentsController::class);
    });
});

require __DIR__.'/auth.php';

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;

class Blog extends Model
{
    use HasFactory, SoftDeletes;

    protected $guarded =[];

    protected $casts = [
        'published_at' => 'datetime',
    ];
    /** Relationship Methods */
    public function author(){
        return $this->belongsTo(User::class , 'user_id');
    }
    public function category(){
        return $this->belongsTo(Category::class);
    }
    public function tags(){
        return $this->belongsToMany(Tag::class)->withTimestamps();
    }
    public function getImagepathAttribute(){
        return '/storage/'.$this->attributes['image_path'];
    }
    public function deleteImage(){
        Storage::delete($this->attributes['image_path']);
    }

    public function scopePublished($query){
        return $query->where('published_at', '<=', now());
    }
    public function scopeSearch($query){
        $searchParam = request()->search;
        if($searchParam){
            $query = $query->where('title', 'like', "%$searchParam%");
        }
        return $query;
    }
    public function comments(){
        return $this->hasMany(Comment::class);
    }
}

app/Http/Controllers/BlogsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Blog\CreateBlogRequest;
use App\Http\Requests\Blogs\UpdateBlogRequest;
use App\Models\Blog;
use App\Models\Category;
use App\Models\Comment;
use App\Models\Tag;
use Illuminate\Http\Request;

class BlogsController extends Controller
{
    public function __construct()
    {
        $this->middleware(['validateAuthor'])->only(['edit', 'update', 'destroy', 'trash', 'publish', 'unpublish']);
        $this->middleware('validateAdmin')->only(['approve', 'unapprove']);
    }

    public function index()
    {
        $authUser = auth()->user();
        if($authUser->isAdmin()){
            $blogs = Blog::with('category')->latest()->paginate(10);  //latest() shows according the latest updated_at in the table!
        }
        else{
            $blogs = Blog::with('category')
                          ->where('user_id', $authUser->id)
                          ->latest()
                          ->paginate(10);
        }

        return view('admin.blogs.index', compact(['blogs']));
    }

    public function create()
    {
        $categories = Category::all();
        $tags = Tag::all();
        return view('admin.blogs.create', compact(['categories', 'tags']));
    }

    public function store(CreateBlogRequest $request)
    {
        // dd($request->draft);
        //Image Upload and return the name of the file which will be created
        $image_path = $request->file('image')->store('blogs');
        $data = $request->only(['title', 'excerpt', 'body', 'category_id', 'published_at']);
        if($request->draft === null){
            $draft = 0;
            $publishedAt = null;

            $data = $request->only(['title', 'excerpt', 'body', 'category_id']);
            $data = array_merge($data, [
                'image_path'=>$image_path,
                'isPublished'=>$draft,
                'published_at' => $publishedAt,
                'isApproved' => 1,
                'user_id'=>auth()->user()->id
            ]);
        }
        else{
            $draft = 1;

            $data = $request->only(['title', 'excerpt', 'body', 'category_id', 'published_at']);
            $data = array_merge($data, [
                'image_path'=>$image_path,
                'isPublished'=>$draft,
                'isApproved' => 1,
                'user_id'=>auth()->user()->id
            ]);
        }
        $blog = Blog::create($data);
        $blog->tags()->attach($request->tags);

        session()->flash('success', 'Blog created successfully...');
        return redirect(route('admin.blogs.index'));
    }

    public function show(string $id)
    {
        //
    }

    public function edit(Blog $blog)
    {
        $categories = Category::all();
        $tags = Tag::all();

        return view('admin.blogs.edit', compact([
            'categories',
            'tags',
            'blog'
        ]));
    }

    public function update(UpdateBlogRequest $request, Blog $blog)
    {
        $data = $request->only(['title', 'excerpt', 'body', 'category_id', 'published_at']);

        if($request->hasFile('image')){
            $image_path = $request->file('image')->store('blogs');
            $blog->deleteImage();  //here deleteImage() is function we have created in Blog model!
            $data = array_merge($data, ['image_path'=>$image_path]);
        }

        $blog->update($data);
        $blog->tags()->sync($request->tags);

        session()->flash('success', 'Blog Updated successfully...');
        return redirect(route('admin.blogs.index'));
    }

    public function trash(Blog $blog){
        $blog->delete();  //here delete() functioin is overridden by the SoftDelete Class ka delete() function jaha deleted_at time is updated not the data is deleted!
        session()->flash('success', 'Blog Deleted successfully...');
        return redirect(route('admin.blogs.index'));
    }

    public function destroy(int $blogId)
    {
        $blog = Blog::onlyTrashed()->find($blogId);
        $blog->deleteImage();
        $blog->forceDelete();

        session()->flash('success', 'Blog Destroyed successfully...');
        return redirect(route('admin.blogs.trashed'));
    }
    public function trashed(){
        $blogs = Blog::with('category')
                      ->where('user_id', auth()->id())
                      ->onlyTrashed()
                      ->latest()
                      ->paginate(10);

        return view('admin.blogs.trashed', compact(['blogs']));
    }
    public function restore(int $blogId){
        $blog = Blog::withTrashed()->find($blogId);
        $blog->restore();

        session()->flash('success', 'Blog Restored successfully...');
        return redirect(route('admin.blogs.index'));
    }

    public function approve(Blog $blog){
        $blog->isApproved = 1;
        $blog->save();

        session()->flash('success', 'Blog Approved successfully...');
        return redirect(route('admin.blogs.index'));
    }
    public function unapprove(Blog $blog){
        $blog->isApproved = 0;
        $blog->save();

        session()->flash('success', 'Blog Unapproved successfully...');
        return redirect(route('admin.blogs.index'));
    }
    public function unpublish(Blog $blog){
        $blog->isPublished = 0;
        $blog->published_at = null;
        $blog->save();

        session()->flash('success', 'Blog Unpublished successfully...');
        return redirect(route('admin.blogs.index'));
    }
    public function publish(Blog $blog){
        $blog->isPublished = 1;
        $blog->published_at = now();
        $blog->save();

        session()->flash('success', 'Blog Published successfully...');
        return redirect(route('admin.blogs.index'));
    }

}

resources/views/admin/blogs/index.blade.php
@extends('admin.layout.app')

@section('main-content')
<div class="container-fluid">
    <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Blogs</h1>
            <a href="{{route('admin.blogs.create')}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">                <i class="fas fa-plus fa-sm text-white-50"></i>
             Create Blog</a>
        </div>
    <!-- End Page Heading -->

    <div class="row">
        <div class="col-md-12">

            @include('admin.layout._alert-messages')

            <table class="table table-bordered table-responsive">
                <thead>
                    <th>ID</th>
                    <th>Image</th>
                    <th>Title</th>
                    <th>Excerpt</th>
                    <th>Category</th>
                    <th>Actions</th>
                    @if (auth()->user()->isAdmin())
                    <th>Approve</th>
                    @endif
                    {{-- @if (auth()->user()->isOwner($blog))
                    <th>Publish Status</th>
                    @endif --}}


                </thead>
                <tbody>
                    @foreach ($blogs as $blog)
                        <tr>
                            <td>{{ $blog->id }}</td>
                            <td>
                                <img src="{{asset($blog->image_path)}}" alt="{{$blog->title}}" width="100px">
                            </td>
                            <td>{{$blog->title}}</td>
                            <td>{{$blog->excerpt}}</td>
                            <td>{{$blog->category->name}}</td>
                            <td>
                                <a href="{{ route('admin.blogs.edit', $blog->id)}}" class="btn btn-primary">
                                    <i class="fas fa-pen"></i>
                                </a>
                                <button class="btn btn-danger mt-1" data-toggle="modal" data-target="#deleteModal"
                                onclick="deleteModalHelper('{{route('admin.blogs.trash', $blog->id)}}' )">
                                    <i class="fa fa-trash"></i>
                                </button>
                            </td>
                            @if (auth()->user()->isAdmin())
                            <td>
                                @if ($blog->isApproved === 1)
                                    <button class="" data-toggle="modal" data-target="#unapproveModal"
                                    onclick="unApproveModalHelper('{{route('admin.blogs.unapprove', $blog->id)}}' )" style="border: none; background-color: #fff">
                                    <i class="fa fa-toggle-on" aria-hidden="true" style="color: green; font-size: 30px"></i>
                                    </button>
                                @else
                                    <button class="" data-toggle="modal" data-target="#approveModal"
                                    onclick="approveModalHelper('{{route('admin.blogs.approve', $blog->id)}}' )" style="border: none; background-color: #fff">
                                    <i class="fa fa-toggle-off" aria-hidden="true" style="color: green; font-size: 30px"></i>
                                    </button>
                                @endif
                            </td>
                            @elseif (auth()->user()->isOwner($blog))
                            <td>
                                @if ($blog->isPublished === 1)
                                    <div class="text-center">
                                        <button class="" data-toggle="modal" data-target="#unpublishModal"
                                        onclick="unpublishModalHelper('{{route('admin.blogs.unpublish', $blog->id)}}' )" style="border: none; background-color: #fff">
                                        <i class="fa fa-toggle-on" aria-hidden="true" style="color: green; font-size: 30px"></i>
                                        </button>
                                        <br>
                                        Published
                                    </div>
                                @else
                                    <div class="text-center">
                                        <button class="" data-toggle="modal" data-target="#publishModal"
                                        onclick="publishModalHelper('{{route('admin.blogs.publish', $blog->id)}}' )" style="border: none; background-color: #fff">
                                        <i class="fa fa-toggle-off" aria-hidden="true" style="color: green; font-size: 30px"></i>
                                        </button>
                                        Unpublished
                                    </div>
                                @endif
                            </td>
                            @endif
                        </tr>
                    @endforeach
                </tbody>
            </table>
            @if ($blogs->count() == 0)
                <p>No Blogs Found!</p>
            @endif
            {{ $blogs->links('vendor.pagination.bootstrap-5')}}
        </div>
    </div>
</div>

 <!-- Approve Modal-->
 <div class="modal fade" id="approveModal" tabindex="-1" role="dialog" aria-labelledby="approveModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form method="POST" action="" id="approveForm">
            @csrf
            @method('PUT')
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="approveModalLabel">Approve this Blog?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Are you sure you want to approve this blog?</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <button class="btn btn-success" type="submit">Approve</button>
                </div>
            </div>
        </form>
    </div>
</div>
<!-- unApprove Modal-->
 <div class="modal fade" id="unapproveModal" tabindex="-1" role="dialog" aria-labelledby="unapproveModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form method="POST" action="" id="unapproveForm">
            @csrf
            @method('PUT')
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="unapproveModalLabel">Unapprove this Blog?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Are you sure you want to Unapprove this blog?</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <button class="btn btn-danger" type="submit">Unapprove</button>
                </div>
            </div>
        </form>
    </div>
</div>

 <!-- Publish Modal-->
 <div class="modal fade" id="publishModal" tabindex="-1" role="dialog" aria-labelledby="publishModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form method="POST" action="" id="publishForm">
            @csrf
            @method('PUT')
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="publishModalLabel">Publish this Blog?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Are you sure you want to publish this blog?</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <button class="btn btn-success" type="submit">Publish</button>
                </div>
            </div>
        </form>
    </div>
</div>

 <!-- Unpublish Modal-->
 <div class="modal fade" id="unpublishModal" tabindex="-1" role="dialog" aria-labelledby="unpublishModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form method="POST" action="" id="unpublishForm">
            @csrf
            @method('PUT')
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="unpublishModalLabel">Unpublish this Blog?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Are you sure you want to Unpublish this blog?</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <button class="btn btn-danger" type="submit">Unpublish</button>
                </div>
            </div>
        </form>
    </div>
</div>
 <!-- DELETE Modal-->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form method="POST" action="" id="deleteForm">
            @csrf
            @method('DELETE')
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete Blog?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Are you sure you want to delete this blog?</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <button class="btn btn-danger" type="submit">Delete</button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection


@section('scripts')
<script>
    function deleteModalHelper(url){
        document.getElementById("deleteForm").setAttribute('action', url);
    }
    function approveModalHelper(url){
        document.getElementById("approveForm").setAttribute('action', url);
    }
    function unApproveModalHelper(url){
        document.getElementById("unapproveForm").setAttribute('action', url);
    }
    function publishModalHelper(url){
        document.getElementById("publishForm").setAttribute('action', url);
    }
    function unpublishModalHelper(url){
        document.getElementById("unpublishForm").setAttribute('action', url);
    }



</script>
@endsection

resources/views/admin/blogs/trashed.blade.php
@extends('admin.layout.app')

@section('main-content')
<div class="container-fluid">
    <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Trashed Blogs</h1>
            <a href="{{route('admin.blogs.create')}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">                <i class="fas fa-plus fa-sm text-white-50"></i>
             Create Blog</a>
        </div>
    <!-- End Page Heading -->

    <div class="row">
        <div class="col-md-12">

            @include('admin.layout._alert-messages')

            <table class="table table-bordered table-responsive">
                <thead>
                    <th>ID</th>
                    <th>Image</th>
                    <th>Title</th>
                    <th>Excerpt</th>
                    {{-- <th>Body</th> --}}
                    <th>Category</th>
                    <th>Actions</th>
                </thead>
                <tbody>
                    @foreach ($blogs as $blog)
                        <tr>
                            <td>{{ $blog->id }}</td>
                            <td>
                                <img src="{{asset($blog->image_path)}}" alt="{{$blog->title}}" width="100px">
                            </td>
                            <td>{{$blog->title}}</td>
                            <td>{{$blog->excerpt}}</td>
                            {{-- <td>{!! $blog->body !!}</td> --}}
                            <td>{{$blog->category->name}}</td>
                            <td>
                                <button class="btn btn-danger" data-toggle="modal" data-target="#restoreModal"
                                onclick="restoreModalHelper('{{route('admin.blogs.restore', $blog->id)}}' )">
                                    <i class="fa fa-recycle"></i>
                                </button>

                                <button class="btn btn-danger" data-toggle="modal" data-target="#deleteModal"
                                onclick="deleteModalHelper('{{route('admin.blogs.destroy', $blog->id)}}' )">
                                    <i class="fa fa-trash"></i>
                                </button>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            @if ($blogs->count() == 0)
                <p>No Blogs Found!</p>
            @endif
            {{ $blogs->links('vendor.pagination.bootstrap-5')}}
        </div>
    </div>
</div>

 <!-- RESTORE Modal-->
 <div class="modal fade" id="restoreModal" tabindex="-1" role="dialog" aria-labelledby="restoreModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form method="POST" action="" id="restoreForm">
            @csrf
            @method('PUT')
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="restoreModalLabel">Restore Blog?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Are you sure you want to restore this blog?</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <button class="btn btn-warning" type="submit">Restore</button>
                </div>
            </div>
        </form>
    </div>
</div>

<!-- End of restore Modal-->

 <!-- DELETE Modal-->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form method="POST" action="" id="deleteForm">
            @csrf
            @method('DELETE')
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete Blog?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Are you sure you want to delete this blog?</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <button class="btn btn-danger" type="submit">Delete</button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection
<!-- End of Delete Modal-->


@section('scripts')
<script>
    function deleteModalHelper(url){
        document.getElementById("deleteForm").setAttribute('action', url);
    }
    function restoreModalHelper(url){
        document.getElementById("restoreForm").setAttribute('action', url);
    }

</script>
@endsection