routes/web.php
<?php

use App\Http\Controllers\BlogsController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\CommentsController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\UsersController;
use Illuminate\Routing\RouteUrlGenerator;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [FrontendController::class, 'index'])->name('home');

Route::get('/categories/{category}/blogs', [FrontendController::class, 'category'])->name('frontend.category');
Route::get('/tags/{tag}/blogs', [FrontendController::class, 'tag'])->name('frontend.tag');
Route::get('/blogs/{blog}', [FrontendController::class, 'show'])->name('frontend.blogs.show');



Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    Route::prefix("/admin")->name('admin.')->group(function(){

        Route::get('/dashboard', function(){
            return view('admin.dashboard');
        })->name('dashboard');

        Route::get('/categories/trashed', [CategoriesController::class, 'trashed'])->name('categories.trashed');
        Route::resource('categories', CategoriesController::class)->except(['show']);
        Route::delete('/categories/{category}/trash', [CategoriesController::class, 'trash'])->name('categories.trash');
        Route::put('/categories/{category}/restore', [CategoriesController::class, 'restore'])->name('categories.restore');

        Route::get('/tags/trashed', [TagsController::class, 'trashed'])->name('tags.trashed');
        Route::resource('tags', TagsController::class)->except(['show']);
        Route::delete('/tags/{tag}/trash', [TagsController::class, 'trash'])->name('tags.trash');
        Route::put('/tags/{tag}/restore', [TagsController::class, 'restore'])->name('tags.restore');

        Route::get('/blogs/trashed', [BlogsController::class, 'trashed'])->name('blogs.trashed');
        Route::resource('blogs', BlogsController::class)->except(['show']);
        Route::delete('/blogs/{blog}/trash', [BlogsController::class, 'trash'])->name('blogs.trash');
        Route::put('/blogs/{blog}/restore', [BlogsController::class, 'restore'])->name('blogs.restore');
        Route::put('/blogs/{blog}/approve', [BlogsController::class, 'approve'])->name('blogs.approve');
        Route::put('/blogs/{blog}/unapprove', [BlogsController::class, 'unapprove'])->name('blogs.unapprove');
        Route::put('/blogs/{blog}/publish', [BlogsController::class, 'publish'])->name('blogs.publish');
        Route::put('/blogs/{blog}/unpublish', [BlogsController::class, 'unpublish'])->name('blogs.unpublish');


        Route::get('/users', [UsersController::class, 'index'])->name('users.index');
        Route::put('/users/{user}/verify', [UsersController::class, 'verify'])->name('users.verify');
        Route::put('/users/{user}/revoke', [UsersController::class, 'revoke'])->name('users.revoke');
        Route::put('/users/{user}/makeadmin', [UsersController::class, 'admin'])->name('users.makeadmin');

        Route::resource('/comments', CommentsController::class);
    });
});

require __DIR__.'/auth.php';

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
    public function blogs(){
        return $this->hasMany(Blog::class);
    }

    public function isAdmin():bool{
        return $this->role === "admin";
    }

    public function isOwner(Blog $blog):bool{
        return $this->id === $blog->user_id;
    }
    public function comments(){
        return $this->belongsToMany(Comment::class);
    }
    public function isVerified(): bool {
        return $this->email_verified_at != null;
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    public function __construct()
    {
        $this->middleware('validateAdmin')->only(['index', 'verify', 'admin', 'revoke']);
    }

    public function index()
    {
        $users = User::paginate(6);
        return view('admin.users.index', compact(['users']));
    }
    public function verify(User $user){
        // dd($user);
        $user->email_verified_at = now();
        $user->save();

        session()->flash('success', 'Email verified successfully...');
        return redirect(route('admin.users.index'));
    }
    public function admin(User $user){
        if(!$user->email_verified_at == null){
            $user->role = 'admin';
            $user->save();

            session()->flash('success', 'Category updated successfully...');
            return redirect(route('admin.users.index'));
        }
        else{
            session()->flash('error', 'You cannot make this user as Admin as its email is not verified yet!');
            return redirect(route('admin.users.index'));
        }
    }
    public function revoke(User $user){
        $userId = auth()->user()->id;
        if($userId === $user->id){
            session()->flash('error', 'You cannot revoke yourself as Admin!');
            return redirect(route('admin.users.index'));
        }
        else{
            $user->role = 'author';
            $user->save();
            session()->flash('success', 'Category updated successfully...');
            return redirect(route('admin.users.index'));
        }
    }

}

resources/views/admin/users/index.blade.php
@extends('admin.layout.app')

@section('main-content')
<div class="container-fluid">
    <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Users</h1>
            <a href="{{route('admin.blogs.index')}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">                <i class="fas fa-plus fa-sm text-white-50"></i>
             Create Admin</a>
        </div>
    <!-- End Page Heading -->

    <div class="row">
        <div class="col-md-12">

            @include('admin.layout._alert-messages')

            <table class="table table-bordered table-responsive">
                <thead>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Is Verified</th>
                    <th>verify Email</th>
                    <th>Role</th>
                    <th>Actions</th>

                </thead>
                <tbody>
                    @foreach ($users as $user)

                        <tr>
                            <td>{{ $user->id }}</td>
                            <td>{{ $user->name}}</td>
                            <td>{{ $user->email}}</td>
                            <td>{{ $user->email_verified_at <= now() ? 'Verified' : '' }}</td>
                            <th class="text-center">
                                @if ($user->email_verified_at == null)
                                    <button class="btn btn-success" data-toggle="modal" data-target="#verifyModal"
                                    onclick="verifyModalHelper('{{route('admin.users.verify', $user->id)}}' )">
                                        <i class="fa fa-check"></i> Verify Now
                                    </button>
                                @else
                                Verified <i class="fa fa-check">
                                @endif
                            </th>
                            <td>{{ $user->role}}</td>
                            <td>
                                @if ($user->role === "author")
                                    <button class="btn btn-primary" data-toggle="modal" data-target="#makeAdminModal"
                                    onclick="makeAdminModalHelper('{{route('admin.users.makeadmin', $user->id)}}' )">
                                        <i class="fa fa-user-plus"></i>
                                    </button> Make as Admin
                                @else
                                    <button class="btn btn-danger" data-toggle="modal" data-target="#revokeAdminModal"
                                    onclick="revokeAdminModalHelper('{{route('admin.users.revoke', $user->id)}}' )">
                                        <i class="fa fa-user-minus"></i>
                                    </button> Revoke as Admin
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            @if ($users->count() == 0)
                <p>No Users Found!</p>
            @endif
            {{ $users->links('vendor.pagination.bootstrap-5')}}
        </div>
    </div>
</div>

<!-- Verify Modal-->
<div class="modal fade" id="verifyModal" tabindex="-1" role="dialog" aria-labelledby="verifyModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form method="POST" action="" id="verifyForm">
            @csrf
            @method('PUT')
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="verifyModalLabel">Verify User?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Are you sure you want to verify this email?</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <button class="btn btn-success" type="submit">Verify</button>
                </div>
            </div>
        </form>
    </div>
</div>
<!-- Make Admin Modal-->
<div class="modal fade" id="makeAdminModal" tabindex="-1" role="dialog" aria-labelledby="makeAdminModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form method="POST" action="" id="makeAdminForm">
            @csrf
            @method('PUT')
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="makeAdminModalLabel">Make Admin?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Are you sure you want to make this User an Admin?</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <button class="btn btn-primary" type="submit">Make Admin</button>
                </div>
            </div>
        </form>
    </div>
</div>

<!-- Revoke Admin Modal-->
<div class="modal fade" id="revokeAdminModal" tabindex="-1" role="dialog" aria-labelledby="revokeAdminModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form method="POST" action="" id="revokeAdminForm">
            @csrf
            @method('PUT')
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="revokeAdminModalLabel">Delete Blog?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Are you sure you want to Revoke this User as Admin?</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <button class="btn btn-danger" type="submit">Revoke</button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection


@section('scripts')
<script>
    function verifyModalHelper(url){
        document.getElementById("verifyForm").setAttribute('action', url);
    }
    function makeAdminModalHelper(url){
        document.getElementById("makeAdminForm").setAttribute('action', url);
    }
    function revokeAdminModalHelper(url){
        document.getElementById("revokeAdminForm").setAttribute('action', url);
    }

</script>
@endsection