routes/web.php
<?php

use App\Http\Controllers\BlogsController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\CommentsController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\UsersController;
use Illuminate\Routing\RouteUrlGenerator;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [FrontendController::class, 'index'])->name('home');

Route::get('/categories/{category}/blogs', [FrontendController::class, 'category'])->name('frontend.category');
Route::get('/tags/{tag}/blogs', [FrontendController::class, 'tag'])->name('frontend.tag');
Route::get('/blogs/{blog}', [FrontendController::class, 'show'])->name('frontend.blogs.show');



Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    Route::prefix("/admin")->name('admin.')->group(function(){

        Route::get('/dashboard', function(){
            return view('admin.dashboard');
        })->name('dashboard');

        Route::get('/categories/trashed', [CategoriesController::class, 'trashed'])->name('categories.trashed');
        Route::resource('categories', CategoriesController::class)->except(['show']);
        Route::delete('/categories/{category}/trash', [CategoriesController::class, 'trash'])->name('categories.trash');
        Route::put('/categories/{category}/restore', [CategoriesController::class, 'restore'])->name('categories.restore');

        Route::get('/tags/trashed', [TagsController::class, 'trashed'])->name('tags.trashed');
        Route::resource('tags', TagsController::class)->except(['show']);
        Route::delete('/tags/{tag}/trash', [TagsController::class, 'trash'])->name('tags.trash');
        Route::put('/tags/{tag}/restore', [TagsController::class, 'restore'])->name('tags.restore');

        Route::get('/blogs/trashed', [BlogsController::class, 'trashed'])->name('blogs.trashed');
        Route::resource('blogs', BlogsController::class)->except(['show']);
        Route::delete('/blogs/{blog}/trash', [BlogsController::class, 'trash'])->name('blogs.trash');
        Route::put('/blogs/{blog}/restore', [BlogsController::class, 'restore'])->name('blogs.restore');
        Route::put('/blogs/{blog}/approve', [BlogsController::class, 'approve'])->name('blogs.approve');
        Route::put('/blogs/{blog}/unapprove', [BlogsController::class, 'unapprove'])->name('blogs.unapprove');
        Route::put('/blogs/{blog}/publish', [BlogsController::class, 'publish'])->name('blogs.publish');
        Route::put('/blogs/{blog}/unpublish', [BlogsController::class, 'unpublish'])->name('blogs.unpublish');


        Route::get('/users', [UsersController::class, 'index'])->name('users.index');
        Route::put('/users/{user}/verify', [UsersController::class, 'verify'])->name('users.verify');
        Route::put('/users/{user}/revoke', [UsersController::class, 'revoke'])->name('users.revoke');
        Route::put('/users/{user}/makeadmin', [UsersController::class, 'admin'])->name('users.makeadmin');

        Route::resource('/comments', CommentsController::class);
    });
});

require __DIR__.'/auth.php';

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'created_by', 'last_updated_by'];

    public function blogs(){
        return $this->hasMany(Blog::class);
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Categories\UpdateCategoryRequest;
use App\Http\Requests\Category\CreateCategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{

    public function __construct()
    {
        $this->middleware(['validateAdmin'])->only(['create','edit', 'update', 'destroy']);
    }

    public function index()
    {

        $categories = Category::latest('updated_at')->paginate(5);  //latest() shows according the latest updated_at in the table!
        return view('admin.categories.index', compact('categories'));
    }

    public function create()
    {
        return view('admin.categories.create');
    }

    public function store(CreateCategoryRequest $request)
    {
        // dd($request);
        // $data = request()->all();
        // request()->validate([
        //     'name'=> 'required|min:3|max:255'
        // ]);
        $userId = auth()->user()->id;
        Category::create([
            'name' => $request->name,
            'created_by'=>$userId,
            'last_updated_by'=>$userId,
        ]);
        // session()->put('success', 'Category created successfully...');
        session()->flash('success', 'Category created successfully...');
        return redirect(route('admin.categories.index'));
    }

    public function show(string $id)
    {
        //
    }

    public function edit(Category $category)
    {
        return view('admin.categories.edit', compact(['category']) );
    }

    public function update(UpdateCategoryRequest $request, Category $category)
    {
        $category->name = $request->name;
        $category->last_updated_by = auth()->user()->id;
        $category->save();

        session()->flash('success', 'Category updated successfully...');
        return redirect(route('admin.categories.index'));
    }

    public function destroy(Request $request, Category $category)
    {
        //TODO: validate if there are post associated with this category then dont delete. else proceed
        if($category->blogs()->count() > 0){
            session()->flash('error', 'Category cannot be deleted as it has blogs associated with it!');
            return redirect(route('admin.categories.index'));
        }

        $category->delete();
        session()->flash('success', 'Category Destroyed successfully!');
        return redirect(route('admin.categories.index'));
    }

}

resources/views/admin/categories/create.blade.php
@extends('admin.layout.app')

@section('main-content')
<div class="container-fluid">
    <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Add New Category</h1>
        </div>
    <!-- End Page Heading -->

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <form action=" {{ route('admin.categories.store')}}" method="POST">
                        @csrf

                        <div class="form-group">
                            <label for="name" class="form-label">Name</label>
                            <input type="text"
                            class="form-control @error('name') border-design text-danger @enderror"
                            value="{{old('name')}}"
                            placeholder="Enter Category Name"
                            id="name"
                            name="name">
                            @error('name')
                                <span class="text-danger">
                                    {{-- {{$errors->has('name') ? 'ERROR' : 'NO ERROR'}} --}}

                                    {{ $errors->first(('name')) }}
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <button type="submit "class="btn btn-primary" name="addCategory">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layout.app')

@section('main-content')
<div class="container-fluid">
    <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Update Category</h1>
        </div>
    <!-- End Page Heading -->

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('admin.categories.update', $category->id)}}" method="POST">
                        @csrf  {{-- Cross Site Request Forgery --}}
                        @method('PUT')
                        <div class="form-group">
                            <label for="name" class="form-label">Name</label>
                            <input type="text"
                            class="form-control"
                            value="{{old('name', $category->name)}}"
                            placeholder="Update Category Name"
                            id="name"
                            name="name">
                            @error('name')
                                <span class="text-danger">
                                    {{-- {{$errors->has('name') ? 'ERROR' : 'NO ERROR'}} --}}

                                    {{ $errors->first(('name')) }}
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <button type="submit "class="btn btn-primary" name="updateCategory">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layout.app')

@section('main-content')
<div class="container-fluid">
    <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Categories</h1>
            <a href="{{route('admin.categories.create')}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm ">
                    <i class="fas fa-plus fa-sm text-white-50"></i>
             Create New Category</a>
        </div>
    <!-- End Page Heading -->

    <div class="row">
        <div class="col-md-12">

            @include('admin.layout._alert-messages')

            <table class="table table-bordered">
                <thead>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Post Count</th>
                    <th>Actions</th>
                </thead>
                <tbody>
                    @foreach ($categories as $category)

                        <tr>
                            <td>{{ $category->id }}</td>
                            <td>{{ $category->name }}</td>
                            <td>0</td>
                            <td>
                                <a href="{{ route('admin.categories.edit', $category->id)}}" class="btn btn-primary">
                                    <i class="fas fa-pen"></i>
                                </a>

                                <button class="btn btn-danger" data-toggle="modal" data-target="#deleteModal"
                                onclick="deleteModalHelper('{{route('admin.categories.destroy', $category->id)}}' )">
                                    <i class="fa fa-trash"></i>
                                </button>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            {{ $categories->links('vendor.pagination.bootstrap-5')}}
        </div>
    </div>
</div>

 <!-- DELETE Modal-->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form method="POST" action="" id="deleteForm">
            @csrf
            @method('DELETE')
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete Category?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Are you sure you want to delete this category?</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <button class="btn btn-danger" type="submit">Delete</button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection


@section('scripts')
<script>
    function deleteModalHelper(url){
        document.getElementById("deleteForm").setAttribute('action', url);
    }
</script>
@endsection