routes/web.php
<?php

use App\Http\Controllers\BlogsController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\CommentsController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\UsersController;
use Illuminate\Routing\RouteUrlGenerator;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [FrontendController::class, 'index'])->name('home');

Route::get('/categories/{category}/blogs', [FrontendController::class, 'category'])->name('frontend.category');
Route::get('/tags/{tag}/blogs', [FrontendController::class, 'tag'])->name('frontend.tag');
Route::get('/blogs/{blog}', [FrontendController::class, 'show'])->name('frontend.blogs.show');



Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    Route::prefix("/admin")->name('admin.')->group(function(){

        Route::get('/dashboard', function(){
            return view('admin.dashboard');
        })->name('dashboard');

        Route::get('/categories/trashed', [CategoriesController::class, 'trashed'])->name('categories.trashed');
        Route::resource('categories', CategoriesController::class)->except(['show']);
        Route::delete('/categories/{category}/trash', [CategoriesController::class, 'trash'])->name('categories.trash');
        Route::put('/categories/{category}/restore', [CategoriesController::class, 'restore'])->name('categories.restore');

        Route::get('/tags/trashed', [TagsController::class, 'trashed'])->name('tags.trashed');
        Route::resource('tags', TagsController::class)->except(['show']);
        Route::delete('/tags/{tag}/trash', [TagsController::class, 'trash'])->name('tags.trash');
        Route::put('/tags/{tag}/restore', [TagsController::class, 'restore'])->name('tags.restore');

        Route::get('/blogs/trashed', [BlogsController::class, 'trashed'])->name('blogs.trashed');
        Route::resource('blogs', BlogsController::class)->except(['show']);
        Route::delete('/blogs/{blog}/trash', [BlogsController::class, 'trash'])->name('blogs.trash');
        Route::put('/blogs/{blog}/restore', [BlogsController::class, 'restore'])->name('blogs.restore');
        Route::put('/blogs/{blog}/approve', [BlogsController::class, 'approve'])->name('blogs.approve');
        Route::put('/blogs/{blog}/unapprove', [BlogsController::class, 'unapprove'])->name('blogs.unapprove');
        Route::put('/blogs/{blog}/publish', [BlogsController::class, 'publish'])->name('blogs.publish');
        Route::put('/blogs/{blog}/unpublish', [BlogsController::class, 'unpublish'])->name('blogs.unpublish');


        Route::get('/users', [UsersController::class, 'index'])->name('users.index');
        Route::put('/users/{user}/verify', [UsersController::class, 'verify'])->name('users.verify');
        Route::put('/users/{user}/revoke', [UsersController::class, 'revoke'])->name('users.revoke');
        Route::put('/users/{user}/makeadmin', [UsersController::class, 'admin'])->name('users.makeadmin');

        Route::resource('/comments', CommentsController::class);
    });
});

require __DIR__.'/auth.php';

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Tag extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'created_by', 'last_updated_by'];

    public function blogs(){
        return $this->belongsToMany(Blog::class)->withTimestamps();
    }
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Tag\CreateTagRequest;
use App\Http\Requests\Tags\UpdateTagRequest;
use App\Models\Category;
use App\Models\Tag;
use Illuminate\Cache\TagSet;
use Illuminate\Http\Request;

class TagsController extends Controller
{
    public function __construct()
    {
        $this->middleware(['validateAdmin'])->only(['create','edit', 'update', 'destroy','trashed', 'trash']);
    }

    public function index()
    {
        $tags = Tag::latest()->paginate(10);  //latest() shows according the latest updated_at in the table!
        return view('admin.tags.index', compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('admin.tags.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(CreateTagRequest $request)
    {
        // dd($request);
        // $data = request()->all();
        // request()->validate([
        //     'name'=> 'required|min:3|max:255'
        // ]);
        $userId = auth()->user()->id;
        Tag::create([
            'name' => $request->name,
            'created_by'=>$userId,
            'last_updated_by'=>$userId,
        ]);
        // session()->put('success', 'Tag created successfully...');
        session()->flash('success', 'Tag created successfully...');
        return redirect(route('admin.tags.index'));
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Tag $tag)
    {
        return view('admin.tags.edit', compact(['tag']) );
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateTagRequest $request, Tag $tag)
    {
        $tag->name = $request->name;
        $tag->last_updated_by = auth()->user()->id;
        $tag->save();

        session()->flash('success', 'Tag updated successfully...');
        return redirect(route('admin.tags.index'));
    }

    public function destroy(Request $request, Tag $tag)
    {
        //TODO: validate if there are post associated with this category then dont delete. else proceed
        if($tag->blogs()->count() > 0){
            session()->flash('error', 'Tag cannot be deleted as it has blogs associated with it!');
            return redirect(route('admin.tags.index'));
        }

        $tag->delete();
        session()->flash('success', 'Tag Destroyed successfully!');
        return redirect(route('admin.tags.index'));
    }
}

resources/views/admin/tags/create.blade.php
@extends('admin.layout.app')

@section('main-content')
<div class="container-fluid">
    <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Add New Tag</h1>
        </div>
    <!-- End Page Heading -->

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('admin.tags.store')}}" method="POST">
                        @csrf

                        <div class="form-group">
                            <label for="name" class="form-label">Name</label>
                            <input type="text"
                            class="form-control"
                            value="{{old('name')}}"
                            placeholder="Enter Tag Name"
                            id="name"
                            name="name">
                            @error('name')
                                <span class="text-danger">
                                    {{-- {{$errors->has('name') ? 'ERROR' : 'NO ERROR'}} --}}

                                    {{ $errors->first(('name')) }}
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <button type="submit "class="btn btn-primary" name="addTag">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/tags/edit.blade.php
@extends('admin.layout.app')

@section('main-content')
<div class="container-fluid">
    <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Update Tag</h1>
        </div>
    <!-- End Page Heading -->

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('admin.tags.update', $tag->id)}}" method="POST">
                        @csrf  {{-- Cross Site Request Forgery --}}
                        @method('PUT')
                        <div class="form-group">
                            <label for="name" class="form-label">Name</label>
                            <input type="text"
                            class="form-control"
                            value="{{old('name', $tag->name)}}"
                            placeholder="Update Tag Name"
                            id="name"
                            name="name">
                            @error('name')
                                <span class="text-danger">
                                    {{-- {{$errors->has('name') ? 'ERROR' : 'NO ERROR'}} --}}

                                    {{ $errors->first(('name')) }}
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <button type="submit "class="btn btn-primary" name="updateTag">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/tags/index.blade.php
@extends('admin.layout.app')

@section('main-content')
<div class="container-fluid">
    <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Tags</h1>
            <a href="{{route('admin.tags.create')}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">                <i class="fas fa-plus fa-sm text-white-50"></i>
             Create New Tag</a>
        </div>
    <!-- End Page Heading -->

    <div class="row">
        <div class="col-md-12">

            @include('admin.layout._alert-messages')

            <table class="table table-bordered">
                <thead>
                    <th>ID</th>
                    <th>Tag Name</th>
                    <th>Tag Count</th>
                    <th>Actions</th>
                </thead>
                <tbody>
                    @foreach ($tags as $tag)
                        <tr>
                            <td>{{ $tag->id }}</td>
                            <td>{{ $tag->name }}</td>
                            <td>0</td>
                            <td>
                                <a href="{{ route('admin.tags.edit', $tag->id)}}" class="btn btn-primary">
                                    <i class="fas fa-pen"></i>
                                </a>
                                <button class="btn btn-danger" data-toggle="modal" data-target="#deleteModal"
                                onclick="deleteModalHelper('{{route('admin.tags.destroy', $tag->id)}}' )">
                                    <i class="fa fa-trash"></i>
                                </button>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            {{ $tags->links('vendor.pagination.bootstrap-5')}}
        </div>
    </div>
    <!-- DELETE Modal-->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form method="POST" action="" id="deleteForm">
            @csrf
            @method('DELETE')
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete Tag?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Are you sure you want to delete this tag?</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <button class="btn btn-danger" type="submit">Delete</button>
                </div>
            </div>
        </form>
    </div>
</div>


@endsection
@section('scripts')
<script>
    function deleteModalHelper(url){
        document.getElementById("deleteForm").setAttribute('action', url);
    }
</script>
@endsection